site_name: "Portfolio IA"
site_author: Juan Paroli
docs_dir: docs
repo_url: https://github.com/jjuuansee/portafolio-ia
repo_name: jjuuansee/portafolio-ia

theme:
  name: material
  language: es
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.annotate       # tips numerados en bloques de código
    - content.tooltips
    - content.tabs.link
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a oscuro
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a claro
  font:
    text: Inter
    code: JetBrains Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jjuuansee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/juan-sebastián-paroli-costa-b71a34263/

extra_css:
  - assets/styles/custom.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/toc-control.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
      block_tag: div
      inline_tag: span

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
      timezone: America/Montevideo
      type: datetime
  - glightbox
  - tags
  - mkdocs-jupyter:
      execute: false           # no ejecutar celdas en el build
      include_source: true     # muestra el icono para descargar .ipynb
  # opcionales:
  # - minify:
  #     minify_html: true
