site_name: "Portfolio IA"
site_author: Juan Paroli Costa
docs_dir: docs
repo_url: https://github.com/jjuuansee/portafolio-ia
repo_name: jjuuansee/portafolio-ia

extra_css:
  - assets/styles/custom.css
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  font: false
  name: material
  # custom_dir: overrides
  icon:
    # logo: myicons/logo
    repo: fontawesome/brands/github
  # favicon: img/favicon.png
  features:
    - toc.follow
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
  language: es
  palette:
    # Light Mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a oscuro
    # Dark Mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a claro

plugins:
  - search
  - glightbox
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - tags
  # opcionales:
  # - minify:
  #     minify_html: true

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jjuuansee/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/juan-sebasti%25C3%25A1n-paroli-costa-b71a34263/?skipRedirect=true
      